-- 1. CATEGORIES TABLE
ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS created_by UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    ADD COLUMN IF NOT EXISTS created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS last_modified_by UUID,
    ADD COLUMN IF NOT EXISTS last_modified_date TIMESTAMP WITHOUT TIME ZONE;

-- 2. POSTS TABLE
ALTER TABLE posts
    ADD COLUMN IF NOT EXISTS created_by UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    ADD COLUMN IF NOT EXISTS created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS last_modified_by UUID,
    ADD COLUMN IF NOT EXISTS last_modified_date TIMESTAMP WITHOUT TIME ZONE;

-- 3. COMMENTS TABLE
ALTER TABLE comments
    ADD COLUMN IF NOT EXISTS created_by UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    ADD COLUMN IF NOT EXISTS created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS last_modified_by UUID,
    ADD COLUMN IF NOT EXISTS last_modified_date TIMESTAMP WITHOUT TIME ZONE;
