name: CI Pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Ensure Maven wrapper is executable
        run: chmod +x ./mvnw

      - name: Run Unit Tests
        run: ./mvnw -B clean verify -Dskip.it -Djacoco.reportFolder=jacoco-ut

      - name: Upload Unit Test JaCoCo Report
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-ut-report
          path: target/site/jacoco-ut/
          retention-days: 1

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Ensure Maven wrapper is executable
        run: chmod +x ./mvnw

      - name: Verify Docker Status
        run: docker info

      - name: Run Integration Tests
        run: ./mvnw -B clean verify -Dskip.ut -Djacoco.reportFolder=jacoco-it

      - name: Upload Integration Test JaCoCo Report
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-it-report
          path: target/site/jacoco-it/
          retention-days: 1

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [ unit-tests, integration-tests ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Ensure Maven wrapper is executable
        run: chmod +x ./mvnw

      - name: Download Unit Test Coverage
        uses: actions/download-artifact@v8
        with:
          name: jacoco-ut-report
          path: target/site/jacoco-ut/

      - name: Download Integration Test Coverage
        uses: actions/download-artifact@v8
        with:
          name: jacoco-it-report
          path: target/site/jacoco-it/

      # Compiles classes safely for analysis, skips test re-runs, and waits for Quality Gate validation
      - name: Code Quality Analysis & Quality Gate Check
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw -B compile sonar:sonar \
            -Dsonar.projectKey=${{ vars.PROJECT_KEY }}\
            -Dsonar.organization=${{ vars.ORGANIZATION_KEY }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-ut/jacoco.xml,target/site/jacoco-it/jacoco.xml \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.exclusions="**/Advice/**,**/Annotations/**,**/Enums/**,**/Entities/**,**/Config/**,**/Constants/**,**/Logging/**,**/Specifications/**,**/*Application.java"

  codeql-analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Auto build
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

  allow-merge:
    runs-on: ubuntu-latest
    needs: [ sonarcloud, codeql-analysis ]
    if: always()
    steps:
      - name: Verify Status
        run: |
          if [[ "${{ needs.sonarcloud.result }}" != "success" || "${{ needs.codeql-analysis.result }}" != "success" ]];
          then
            echo "Pipeline Gate Failed."
            exit 1
          fi
          echo "Pipeline Passed."